### ISSUE TITLE
Error running PyNetMonitor script due to missing file 'librespeed-cli

### ISSUE THREAD

**Issue by Ortieez** [DEPSTRCZ/PyNetMonitor#1]
When attempting to run the PyNetMonitor script, the job "SpeedTestInterval" raised an exception with the following error message:

```
Job "SpeedTestInterval (trigger: interval[0:01:00], next run at: 2023-02-14 17:31:19 CET)" raised an exception
Traceback (most recent call last):
  File "/home/ortieez/.local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ortieez/Downloads/PyNetMonitor-Linux64/PyNetMonitor-run.py", line 57, in SpeedTestInterval
    run = subprocess.run(["librespeed-cli","--json"],capture_output=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'librespeed-cli'
```

**Comment by DEPSTRCZ** [comment]
Did you followed the setup instructions?

**Comment by Ortieez** [comment]
Nevermind works 👍🏼
